---
title: "BC Fed-Prov Realtime Hydrometric Network Lag"
author: "Sam Albers"
date: "Generated on: `r Sys.Date()` "
output:
  knitr:::html_vignette:
    toc: true
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
# Copyright 2017 Province of British Columbia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, messages = FALSE, fig.width = 8, fig.height = 12)

library(tidyhydat)
library(hydrolook)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)


```


# Introduction
```{r}
bc_lag <- check_realtime_lag(STATION_NUMBER = "ALL", PROV_TERR_STATE_LOC = "BC")
#bc_lag <- check_realtime_lag(STATION_NUMBER = c("08NL071","08LG048"), PROV_TERR_STATE_LOC = "BC")
bc_lag
```

# Summary
```{r, echo = FALSE}
lag_tbl <- bc_lag %>%
  filter(!is.na(time_lag_num)) %>%
  summarise_at(vars(time_lag_num), funs(mean, median, sd, min, max))

kable(lag_tbl)

```

```{r, warning=FALSE}
num_stations = nrow(bc_lag)

bc_lag %>%
  mutate(Grouping = case_when(
   time_lag_num >= 1000 ~ "Over 1000 minutes", 
   time_lag_num < 1000 ~ "Under 1000 minutes"
  )  ) %>%
  filter(!is.na(Grouping)) %>%
  ggplot(aes(x = time_lag_num)) +
  geom_histogram() +
  geom_rug() +
  labs(x = "Difference between upload time and most recent observations (minutes)",
       y = "Number of Ocurrences",
       title = paste0("Realtime Hydrometric Station Data Lag (n = ",num_stations,")"),
       subtitle = "Each station in BC was pinged for the most recent hydrometric observation. The difference between this value and the time of data upload is considered the lag time",
       caption = "Generated by Sam Albers - BC Ministry of Environment"
       ) +
  facet_wrap(~Grouping, scales = "free_x") +
  theme_minimal()
```

